server:
  port: 3000
dubbo:
  application:
    name: dongdongshop_app
  registry:
    address: zookeeper://127.0.0.1:2181
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.198.129
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

rocketmq:
  name-server: 192.168.198.129:9876
  producer:
    group: group2

shiro:
  loginUrl: /


