server:
  port: 4000
dubbo:
  application:
    name: dongdongshop_freemarker_service
  registry:
    address: zookeeper://127.0.0.1:2181
rocketmq:
  name-server: 192.168.198.129:9876
  producer:
    group: group1